parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  no-template-curly-in-string: off
  quotes: off
  "@typescript-eslint/interface-name-prefix": off
  eol-last: off
  arrow-parens: off
  "@typescript-eslint/no-namespace": off
  max-len:
    - error
    - code: 150
  sort-keys: off
  comma-dangle: off
  no-unused-expressions: error
  camelcase: error
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/indent":
    - error
    - 2

  # recommendation overrides
  "@typescript-eslint/array-type": warn
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/member-delimiter-style": warn
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-parameter-properties": warn
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/no-var-requires": off
  no-case-declarations: warn
  no-console: warn
  no-constant-condition: warn
  no-inner-declarations: warn
  # duplicate of @typescript-eslint/semi
  semi: off
  # duplicate of "camelcase"
  "@typescript-eslint/camelcase": off

  # tslint:recommended rules equivalents
  arrow-body-style: error
  "@typescript-eslint/ban-types":
    - error
    - types:
        Object:
          message: "Avoid using the `Object` type. Did you mean `object`?"
          fixWith: object
        Function: "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."
        Boolean:
          message: "Avoid using the `Boolean` type. Did you mean `boolean`?"
          fixWith: boolean
        Number:
          message: "Avoid using the `Number` type. Did you mean `number`?"
          fixWith: number
        String:
          message: "Avoid using the `String` type. Did you mean `string`?"
          fixWith: string
        Symbol:
          message: "Avoid using the `Symbol` type. Did you mean `symbol`?"
          fixWith: symbol
  "@typescript-eslint/prefer-function-type": error
  guard-for-in: error
  "@typescript-eslint/member-ordering":
    - error
    - default:
      - 'static-method'
      - 'instance-field'
      - 'static-field'
      - 'constructor'
      - 'instance-method'
  new-parens: error
  # FIXME https://github.com/typescript-eslint/typescript-eslint/releases/v1.14.0
  # "@typescript-eslint/consistent-type-assertions": error
  no-caller: error
  no-bitwise: error
  no-new-wrappers: error
  no-eval: error
  no-shadow: error
  dot-notation: error
  no-throw-literal: error
  no-switch-case-fall-through: off
  no-undef-init: error
  quote-props:
    - error
    - consistent-as-needed
  object-shorthand: error
  one-var:
    - error
    - never
  "@typescript-eslint/prefer-for-of": error
  radix: error
  "@typescript-eslint/semi": error
  eqeqeq: error
  "@typescript-eslint/unified-signatures": error
