parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  semi: error
  no-template-curly-in-string: off
  quotes: off
  "@typescript-eslint/interface-name-prefix": off
  eol-last: off
  arrow-parens: off
  "@typescript-eslint/no-namespace": off
  max-len: 
    - error
    - code: 150
  sort-keys: off
  comma-dangle: off
  no-unused-expressions: error
  camelcase: 
    - error
    - allow:
      - "child_process"
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/indent": 
    - error
    - 2

  # recommendation overrides
  "@typescript-eslint/array-type": warn
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/member-delimiter-style": warn
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-parameter-properties": warn
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/no-var-requires": off
  "no-case-declarations": warn
  "no-console": warn
  "no-constant-condition": warn

  # duplicate of "camelcase"
  "@typescript-eslint/camelcase": off