github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

image: jsii/superchain:1-buster-slim-node16

tasks:
  - init: |
      (
        set -e
        yarn install
        export NODE_OPTIONS=--max-old-space-size=8192
        # build the entire repository 
        npx lerna run build
      )

vscode:
  extensions:
    - dbaeumer.vscode-eslint
