github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

image: jsii/superchain:1-buster-slim-node16

tasks:
  - init: yarn install
  # build for aws-cdk-lib
  - init: cd packages/aws-cdk-lib && NODE_OPTIONS=--max-old-space-size=8192 ../../scripts/buildup
  # build for framework-integ
  - init: cd packages/@aws-cdk-testing/framework-integ && NODE_OPTIONS=--max-old-space-size=8192 ../../../scripts/buildup

vscode:
  extensions:
    - dbaeumer.vscode-eslint
