# See https://doc.mergify.io

pull_request_rules:
  - name: automatic merge non-sensitive
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now being automatically merged.
      merge:
        strict: smart
        method: squash
        strict_method: squash
      delete_head_brancH: {}
      dismiss_reviews: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=^(blocked|do-not-merge)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=AWS CodeBuild us-east-1 (aws-cdk-build)
      - status-success=Semantic Pull Request
  - name: comment checklist
    actions:
      comment:
        message:
        "### Pull Request Checklist
        * [ ] Testing
          - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
          - __CLI change?:__ coordinate update of integration tests with team
          - __cdk-init template change?:__ coordinated update of integration tests with team
        * [ ] Docs
          - __jsdocs__: All public APIs documented
          - __README__: README and/or documentation topic updated
          - __Design__: For significant features, design document added to `design` folder
        * [ ] Title and Description
          - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
          - __Title__: use lower-case and doesn't end with a period
          - __Breaking?__: last paragraph: 'BREAKING CHANGE: <describe what changed + link for details>'
          - __Issues__: Indicate issues fixed via: '**Fixes #xxx**' or '**Closes #xxx**'
        * [ ] Sensitive Modules (requires 2 PR approvers)
          - IAM Policy Document (in @aws-cdk/aws-iam)
          - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
          - Grant APIs (only if not based on official documentation with a reference)"
    conditions:
      - base=master
  - name: remove stale reviews
    actions:
      dismiss_reviews: {}
    conditions:
      - base=master
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - -status-success=Semantic Pull Request