version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    commands:

      # baked in our image.
      # tried starting this on image boot but CodeBuild entrypoint shananigens got the best of me.
      # https://github.com/aws/aws-codebuild-docker-images/issues/157#issuecomment-457424620
      - /root/ecr-proxy/start.sh

      # debug - disable dockerhub
      - echo "127.0.0.1       registry-1.docker.io" >> /etc/hosts
      - cat /etc/hosts
      - docker pull alpine

      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - 'if ${BUMP_CANDIDATE:-false}; then /bin/bash ./scripts/bump-candidate.sh; fi'
      - /bin/bash ./scripts/align-version.sh
      # - /bin/bash ./build.sh
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && /bin/bash ./pack.sh"
artifacts:
  files:
    - "**/*"
  base-directory: dist
reports:
  jest-tests:
    files:
      - "**/junit.xml"
    file-format: JunitXml
