version: 0.2

phases:
  install:
    commands:
      # CodeBuild always runs as root, allow npm to operate as such
      - npm config set unsafe-perm true
      - mkdir ${HOME}/aws-cdk && cd ${HOME}/aws-cdk
      # Configure git and git credentials
      - git config --global user.email "${COMMIT_EMAIL}"
      - git config --global user.name "${COMMIT_USERNAME}"
      - echo "Retrieving ssh key from secretsmanager & ssh git setup."
      - aws secretsmanager get-secret-value --secret-id ${SSH_KEY_SECRET_ARN} --output=text --query=SecretString > ~/.ssh/id_rsa;
      - mkdir -p ~/.ssh;
      - chmod 0600 ~/.ssh/id_rsa ~/.ssh/config;
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts;
      - git clone git@github.com:aws/aws-cdk.git -b feat/repo-restructure .
      - git checkout ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
      - yarn install --frozen-lockfile
  build:
    commands:
      - cd ${HOME}/aws-cdk
      - npx lerna run build --scope @aws-cdk/remodel --include-dependencies
      - npx remodel ${PWD} --tmp-dir ${HOME}/remodel --no-clean --dry-run
      - codebuild-breakpoint
  post_build:
    commands:
      - cd ${HOME}/remodel
      - git checkout -B feat/remodel
      - git add -A
      - git commit -m "Execute remodel"
      - git remote add aws-cdk git@github.com:aws/aws-cdk.git
      - git push -u aws-cdk feat/remodel

artifacts:
  files:
    - "**/*"
  base-directory: ${HOME}/remodel
