version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  build:
    commands:
      - /bin/bash ./build.sh
  post_build:
    commands:
      - /bin/bash if [ -f ".BUILD_COMPLETED" ]; then ./pack.sh; else echo "No .BUILD_COMPLETED file, failing"; exit 1; fi
      - /bin/bash if [ -f ".BUILD_COMPLETED" ]; then ./bundle-beta.sh; fi
artifacts:
  files:
    - "**/*"
  base-directory: dist
