name: Pull Request Linter
description: Execute validation rules on GitHub Pull Requests
inputs:
  check:
    description: Which check to execute
    required: true    
runs:
  using: node12
  main: index.js