name: issue-graduation-manager
on: 
  schedule:
    - cron: "0 0 * * 0"

jobs:
  issue-graduation-manager:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: kaizen3031593/issue-graduation-manager@main
        id: grad-manager
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          original-label: p2
          new-label: p1
          skip-label: no-graduation
          graduation-threshold: 20
      - uses: kaizen3031593/pr-triage-manager@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          on-pulls: ${{ steps.grad-manager.outputs.linked-pulls }}
