name: Lock Closed Issues and PRs with message

on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed]

jobs:
  auto_comment:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            Comments on closed issues and PRs are hard for our team to see. 
            If you need help, please open a new issue that references this one.
            If you wish to keep having a conversation with other community members under this issue feel free to do so.
  lock:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: auto_comment
    steps:
      - name: Lock closed PRs and issues
        uses: dessant/lock-threads@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          pr-inactive-days: 0
          issue-inactive-days: 0
          issue-lock-reason: "resolved"
          pr-lock-reason: "resolved"
