name: Lock Closed Issues and PRs with message

on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed]

jobs:
  auto_comment:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            We appreciate you taking the time to provide feedback. However, GitHub does not send notifications for new comments on closed issues or pull requests. This makes it easy for our team to miss important updates in these closed discussions.

            If you have an ongoing question or need further assistance, please open a new issue and reference the original one. That will ensure we receive a notification and can better track and address your concerns.
  lock:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: auto_comment # only run after comment is complete
    steps:
      - name: Lock closed issue or PR
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            ISSUE_NUMBER=${{ github.event.issue.number }}
            ISSUE_URL=https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/lock
          else
            ISSUE_NUMBER=${{ github.event.pull_request.number }}
            ISSUE_URL=https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/lock
          fi

          curl -s -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          ${ISSUE_URL} \
          -d @- <<EOF
          {
            "lock_reason": "resolved"
          }
          EOF
