# https://octokit.github.io/rest.js
# https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts

name: PR Linter
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
      - edited

jobs:
  mandatory-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: cd .github/actions/prlinter && npm ci

      - name: Validate
        uses: ./.github/actions/prlinter
        with:
          check: MANDATORY_CHANGES
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  commit-message:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: cd .github/actions/prlinter && npm ci

      - name: Validate
        uses: ./.github/actions/prlinter
        with:
          check: COMMIT_MESSAGE
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
