on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Download regions
        id: download
        run: |
          response=$(curl https://d3akamx322av4k.cloudfront.net/regions.json)
          echo "REGIONS=${response}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        env:
          REGIONS: ${{ steps.download.outputs.REGIONS }}
        with:
          script: |
            const script = require('./scripts/script.js')
            await script({github, context, core})