# Automated actions for PRs against the v2-main branch
name: v2
on:
  pull_request:
    branches:
      - v2-main
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  # Run yarn pkglint on merge forward PRs and commit the results
  pkglint:
    if: contains(github.event.pull_request.labels.*.name, 'pr/forward-merge')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: lint
        run: |-
          yarn install --frozen-lockfile
          yarn pkglint
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'automatic pkglint fixes'

  # Approve automated PRs
  auto-approve:
    if: >
      (github.event.pull_request.user.login == 'aws-cdk-automation'
      || github.event.pull_request.user.login == 'dependabot-preview')
      && contains(github.event.pull_request.labels.*.name, 'pr/auto-approve')
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

  core-label:
    env:
      CORE_MEMBERS: eladb,RomainMuller,garnaat,nija-at,skinny85,rix0rrr,NGL321,Jerry-AWS,MrArnoldPalmer,NetaNir,iliapolo,njlynch,ericzbeard,ccfife,fulghum,pkandasamy91,SoManyHs,uttarasridhar
    if: contains(env.CORE_MEMBERS.split(','), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        add-labels: "core-contributor"
        ignore-if-labeled: true
        github-token: "${{ secrets.GITHUB_TOKEN }}"
